/**
 * Publishes the catalog freshness report produced by `zkr drift`.
 *
 * Loaded by `.github/workflows/drift.yml` through `actions/github-script`, which
 * invokes the exported function with its `{ github, context, core }` toolkit.
 * The function reads the drift findings from `drift.json` in the workspace,
 * keeps only genuine drift, and opens, updates, or closes one tracking issue
 * accordingly. It never edits the catalog; corrections flow only through a PR.
 */
const fs = require("fs");

module.exports = async ({ github, context, core }) => {
    const findings = JSON.parse(fs.readFileSync("drift.json", "utf8"));
    const kinds = ["status-drift", "spec-drift", "unparsable", "unreachable"];
    const drift = findings.filter((f) => kinds.includes(f.kind));

    const { owner, repo } = context.repo;
    const label = "drift";
    const marker = "<!-- zkr-drift-report -->";
    const title = "Catalog drift: upstream proposals have changed";

    const open = await github.paginate(github.rest.issues.listForRepo, {
        owner,
        repo,
        state: "open",
        labels: label,
        per_page: 100,
    });
    const existing = open.find((i) => i.body && i.body.includes(marker));

    if (drift.length === 0) {
        if (existing) {
            await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: existing.number,
                body: "Upstream drift has cleared; the catalog matches every source again. Closing.",
            });
            await github.rest.issues.update({
                owner,
                repo,
                issue_number: existing.number,
                state: "closed",
            });
        }
        core.info("No drift; nothing to report.");
        return;
    }

    const reason = (e) =>
        typeof e === "string"
            ? e
            : Object.entries(e).map(([k, v]) => `${k} (${v})`).join("");
    const describe = (f) => {
        switch (f.kind) {
            case "status-drift":
                return `- \`${f.id}\` status: catalog \`${f.catalog}\` -> upstream \`${f.upstream}\` (native \`${f.native}\`)`;
            case "spec-drift":
                return `- \`${f.id}\` spec: catalog ${f.catalog} -> canonical ${f.canonical}`;
            case "unparsable":
                return `- \`${f.id}\` upstream status unreadable at ${f.url}: ${reason(f.error)}`;
            case "unreachable":
                return `- \`${f.id}\` upstream unreachable at ${f.url}: ${f.error}`;
        }
    };

    const run = `${context.serverUrl}/${owner}/${repo}/actions/runs/${context.runId}`;
    const body = [
        marker,
        "",
        `The scheduled freshness check found ${drift.length} catalog entr${drift.length === 1 ? "y" : "ies"} that no longer match the upstream proposal repositories. Each line shows the recorded value followed by the upstream value. Apply each fix through a normal pull request that edits \`data/\`; this issue updates on every run and closes automatically once the catalog is back in sync.`,
        "",
        ...drift.map(describe),
        "",
        "---",
        `Generated by the \`Drift\` workflow from \`zkr drift\`. [Run log](${run}).`,
    ].join("\n");

    try {
        await github.rest.issues.getLabel({ owner, repo, name: label });
    } catch (e) {
        if (e.status !== 404) throw e;
        await github.rest.issues.createLabel({
            owner,
            repo,
            name: label,
            color: "fbca04",
            description: "A catalog entry has drifted from its upstream proposal",
        });
    }

    if (existing) {
        await github.rest.issues.update({ owner, repo, issue_number: existing.number, body });
        core.info(`Updated drift issue #${existing.number}.`);
    } else {
        const created = await github.rest.issues.create({ owner, repo, title, labels: [label], body });
        core.info(`Opened drift issue #${created.data.number}.`);
    }
};
